version: 2
jobs:
  build:
    docker:
      - image: gcc:5
    steps:
      - checkout
      - run:
          name: test with python2.7
          command: |
            ./waf configure
            ./waf --check
      - run:
          name: build with python2.7
          command: |
            ./waf build
            ./waf install
